/*
 * array.h - template header: read-only view, mutable span, and growable
 *           arena-backed array for a single element type.
 *
 * One inclusion of this header defines the View, Span, and Array types for
 * a given element type, plus conversion helpers and all array operations.
 *
 * Define before including:
 *   ARRAY_T      element type (required)
 *   ARRAY_NAME   name for the Array struct (optional; default: rc_array_##ARRAY_T)
 *   ARRAY_VIEW   name for the View  struct (optional; default: rc_view_##ARRAY_T)
 *   ARRAY_SPAN   name for the Span  struct (optional; default: rc_span_##ARRAY_T)
 *
 * All macros defined before inclusion are undefined by this header.
 *
 * Generated types
 * ---------------
 *   ARRAY_VIEW: { const ARRAY_T *data; uint32_t num; }              read-only slice
 *   ARRAY_SPAN: {       ARRAY_T *data; uint32_t num; }              mutable  slice
 *   ARRAY_NAME: {       ARRAY_T *data; uint32_t num; uint32_t cap; } growable array
 *
 * Bounds-checked access (once-only, type-generic)
 * ------------------------------------------------
 * RC_AT(v, i), RC_VIEW_AT(v, i), and RC_SPAN_AT(s, i) are defined on the
 * first inclusion and work on all three container types without conversion —
 * they operate directly on the .data pointer and .num field:
 *
 *   int x = RC_AT(my_view, 2);          // rc_view_int  — const lvalue
 *   int y = RC_AT(my_span, 2);          // rc_span_int  — mutable lvalue
 *   int z = RC_AT(my_array, 2);         // rc_array_int — mutable lvalue
 *   RC_AT(my_array, 1) = 99;            // lvalue assignment
 *   RC_VIEW_AT / RC_SPAN_AT are aliases for RC_AT.
 *
 * Bounds failures trigger RC_DEBUG_BREAK_.  With NDEBUG the check
 * reduces to a discarded void expression that any optimiser will elide.
 *
 * Conversion
 * ----------
 * (a) Per-type inline functions generated by this header (named after ARRAY_NAME
 *     and ARRAY_SPAN, so custom names are reflected in the function names):
 *       ARRAY_SPAN_as_view(ARRAY_SPAN s)     → ARRAY_VIEW  adds const
 *       ARRAY_NAME_as_view(ARRAY_NAME *arr)  → ARRAY_VIEW  adds const, drops cap
 *       ARRAY_NAME_as_span(ARRAY_NAME *arr)  → ARRAY_SPAN  drops cap
 *
 * Sub-slice functions (all static inline)
 * ----------------------------------------
 * All accept a zero-based start index and an element count; both are clamped
 * to the source range so the result is always a valid, non-dangling slice.
 *
 *   ARRAY_VIEW_subview(ARRAY_VIEW v, uint32_t start, uint32_t count) → ARRAY_VIEW
 *   ARRAY_SPAN_subspan(ARRAY_SPAN s, uint32_t start, uint32_t count) → ARRAY_SPAN
 *   ARRAY_SPAN_subview(ARRAY_SPAN s, uint32_t start, uint32_t count) → ARRAY_VIEW
 *   ARRAY_NAME_subspan(ARRAY_NAME *arr, uint32_t start, uint32_t count) → ARRAY_SPAN
 *   ARRAY_NAME_subview(ARRAY_NAME *arr, uint32_t start, uint32_t count) → ARRAY_VIEW
 *
 * (b) Type-parameterised macros (once-only):
 *       RC_AS_VIEW(T, x)  — compound-literal rc_view_T from any x with .data/.num
 *       RC_AS_SPAN(T, x)  — compound-literal rc_span_T from any x with .data/.num
 *
 * Arena parameter
 * ---------------
 * Every function that may reallocate takes rc_arena *a as its last parameter.
 * NULL is valid when no reallocation is needed; the function asserts if a
 * reallocation would be required and a == NULL, or on OOM.
 *
 * Growth strategy
 * ---------------
 * new_cap starts at max(current_cap, 8) and doubles until >= requested cap.
 */

#include "richc/template_util.h"
#include "richc/arena.h"
#include <string.h>

/* ===== once-only section: type-generic helpers and conversion macros ===== */

#ifndef RC_ARRAY_ONCE_
#define RC_ARRAY_ONCE_

/*
 * Bounds-checked element access.
 *
 * RC_AT(v, i) works on any container with .data and .num fields (View, Span,
 * Array).  In debug mode a failing bounds check triggers RC_DEBUG_BREAK_
 * without going through stdio or abort().  In release mode it reduces to
 * a plain subscript with zero overhead.
 */
#define RC_AT(v, i) \
    (*(RC_ASSERT((uint32_t)(i) < (v).num), (v).data + (uint32_t)(i)))

/* Aliases. */
#define RC_VIEW_AT(v, i)  RC_AT((v), (i))
#define RC_SPAN_AT(s, i)  RC_AT((s), (i))

/*
 * Type-parameterised conversion macros.
 *
 * x must have .data and .num fields and is evaluated twice; avoid
 * side effects.
 *
 *   RC_AS_VIEW(T, x)  — produces rc_view_T from x; always safe.
 *   RC_AS_SPAN(T, x)  — produces rc_span_T from x; emits a const-discard
 *                        warning when x is a rc_view_T.
 */
#define RC_AS_VIEW(T, x)  ((RC_CONCAT(rc_view_, T)) {(x).data, (x).num})
#define RC_AS_SPAN(T, x)  ((RC_CONCAT(rc_span_, T)) {.data = (x).data, .num = (x).num})

/*
 * Brace-enclosed initializers from a C array expression.
 *
 * RC_VIEW(arr) and RC_SPAN(arr) may only be used in initialisation context
 * (i.e. as the right-hand side of a variable declaration), not as function
 * arguments.  The element count is derived at compile time via sizeof, so
 * arr must be a true array expression — not a pointer.
 *
 *   rc_view_int  v = RC_VIEW(arr);
 *   rc_span_int  s = RC_SPAN(arr);
 */
#define RC_VIEW(arr) {(arr), (uint32_t)(sizeof(arr) / sizeof((arr)[0]))}
#define RC_SPAN(arr) {.data = (arr), .num = (uint32_t)(sizeof(arr) / sizeof((arr)[0]))}

#endif /* RC_ARRAY_ONCE_ */

/* ===== per-type section ===== */

#ifndef ARRAY_T
#  error "ARRAY_T must be defined before including array.h"
#endif

/* ---- optional macro defaults ---- */

#ifndef ARRAY_NAME
#  define ARRAY_NAME RC_CONCAT(rc_array_, ARRAY_T)
#endif

#ifndef ARRAY_VIEW
#  define ARRAY_VIEW RC_CONCAT(rc_view_, ARRAY_T)
#endif

#ifndef ARRAY_SPAN
#  define ARRAY_SPAN RC_CONCAT(rc_span_, ARRAY_T)
#endif

/* ---- internal function name macros ---- */

#define ARRAY_SPAN_AS_VIEW_   RC_CONCAT(ARRAY_SPAN, _as_view)
#define ARRAY_AS_VIEW_        RC_CONCAT(ARRAY_NAME, _as_view)
#define ARRAY_AS_SPAN_        RC_CONCAT(ARRAY_NAME, _as_span)
#define ARRAY_VIEW_SUBVIEW_   RC_CONCAT(ARRAY_VIEW, _subview)
#define ARRAY_SPAN_SUBSPAN_   RC_CONCAT(ARRAY_SPAN, _subspan)
#define ARRAY_SPAN_SUBVIEW_   RC_CONCAT(ARRAY_SPAN, _subview)
#define ARRAY_SUBSPAN_        RC_CONCAT(ARRAY_NAME, _subspan)
#define ARRAY_SUBVIEW_        RC_CONCAT(ARRAY_NAME, _subview)
#define ARRAY_RESERVE_        RC_CONCAT(ARRAY_NAME, _reserve)
#define ARRAY_PUSH_           RC_CONCAT(ARRAY_NAME, _push)
#define ARRAY_POP_            RC_CONCAT(ARRAY_NAME, _pop)
#define ARRAY_PUSH_N_         RC_CONCAT(ARRAY_NAME, _push_n)
#define ARRAY_APPEND_VIEW_    RC_CONCAT(ARRAY_NAME, _append_view)
#define ARRAY_RESIZE_         RC_CONCAT(ARRAY_NAME, _resize)
#define ARRAY_INSERT_         RC_CONCAT(ARRAY_NAME, _insert)
#define ARRAY_INSERT_N_ZERO_  RC_CONCAT(ARRAY_NAME, _insert_n_zero)
#define ARRAY_INSERT_VIEW_    RC_CONCAT(ARRAY_NAME, _insert_view)
#define ARRAY_REMOVE_         RC_CONCAT(ARRAY_NAME, _remove)
#define ARRAY_REMOVE_N_       RC_CONCAT(ARRAY_NAME, _remove_n)
#define ARRAY_REMOVE_SWAP_    RC_CONCAT(ARRAY_NAME, _remove_swap)

/* ---- generated structs ---- */

/*
 * View: read-only slice.  Base type for the family.
 */
typedef struct {
    const ARRAY_T *data;
    uint32_t       num;
} ARRAY_VIEW;

/*
 * Span: mutable slice.
 *
 * The anonymous union gives two access paths to the same memory:
 *   .view        — rc_view_T (const pointer); valid upcast, no function call needed
 *   .data / .num — mutable fields via the anonymous struct
 *
 * Union type punning between T* and const T* is well-defined in C because
 * pointers to qualified versions of compatible types share the same
 * representation (C11 §6.2.5p26).
 */
typedef struct {
    union {
        ARRAY_VIEW view;                              /* read-only upcast   */
        struct { ARRAY_T *data; uint32_t num; };      /* mutable fields     */
    };
} ARRAY_SPAN;

/*
 * Array: growable, arena-backed.
 *
 * The anonymous union extends the same pattern:
 *   .span        — rc_span_T (mutable slice, drops cap)
 *   .view        — rc_view_T (read-only slice, drops cap)
 *   .data / .num — mutable fields via the anonymous struct
 *   .cap         — capacity (outside the union)
 */
typedef struct {
    union {
        ARRAY_SPAN span;                              /* mutable slice      */
        ARRAY_VIEW view;                              /* read-only slice    */
        struct { ARRAY_T *data; uint32_t num; };      /* direct field access */
    };
    uint32_t cap;
} ARRAY_NAME;

/* ---- generated conversion functions ---- */

/* rc_span_T.view as a named function (span → view, adds const). */
static inline ARRAY_VIEW ARRAY_SPAN_AS_VIEW_(ARRAY_SPAN s)  { return s.view;    }

/* Return a read-only view of the current array contents. */
static inline ARRAY_VIEW ARRAY_AS_VIEW_(ARRAY_NAME *arr)     { return arr->view; }

/* Return a mutable span over the current array contents. */
static inline ARRAY_SPAN ARRAY_AS_SPAN_(ARRAY_NAME *arr) {return arr->span; }

/* ---- generated sub-slice functions ---- */

/*
 * Sub-slice helpers.  start and count are both clamped to the source's
 * available range, so the result is always a valid, non-dangling slice.
 * No assertions fire regardless of the values supplied.
 */

/* Return a sub-view of v starting at start, spanning count elements. */
static inline ARRAY_VIEW ARRAY_VIEW_SUBVIEW_(ARRAY_VIEW v,
                                              uint32_t start, uint32_t count)
{
    if (start > v.num) start = v.num;
    uint32_t avail = v.num - start;
    if (count > avail) count = avail;
    return (ARRAY_VIEW) {v.data + start, count};
}

/* Return a mutable sub-span of s starting at start, spanning count elements. */
static inline ARRAY_SPAN ARRAY_SPAN_SUBSPAN_(ARRAY_SPAN s,
                                              uint32_t start, uint32_t count)
{
    if (start > s.num) start = s.num;
    uint32_t avail = s.num - start;
    if (count > avail) count = avail;
    return (ARRAY_SPAN) {.data = s.data + start, .num = count};
}

/* Return a read-only sub-view of s starting at start, spanning count elements. */
static inline ARRAY_VIEW ARRAY_SPAN_SUBVIEW_(ARRAY_SPAN s,
                                              uint32_t start, uint32_t count)
{
    if (start > s.num) start = s.num;
    uint32_t avail = s.num - start;
    if (count > avail) count = avail;
    return (ARRAY_VIEW) {s.data + start, count};
}

/* Return a mutable sub-span of arr starting at start, spanning count elements. */
static inline ARRAY_SPAN ARRAY_SUBSPAN_(ARRAY_NAME *arr,
                                         uint32_t start, uint32_t count)
{
    if (start > arr->num) start = arr->num;
    uint32_t avail = arr->num - start;
    if (count > avail) count = avail;
    return (ARRAY_SPAN) {.data = arr->data + start, .num = count};
}

/* Return a read-only sub-view of arr starting at start, spanning count elements. */
static inline ARRAY_VIEW ARRAY_SUBVIEW_(ARRAY_NAME *arr,
                                         uint32_t start, uint32_t count)
{
    if (start > arr->num) start = arr->num;
    uint32_t avail = arr->num - start;
    if (count > avail) count = avail;
    return (ARRAY_VIEW) {arr->data + start, count};
}

/* ---- generated array functions ---- */

/*
 * Ensure capacity for at least cap elements.  No-op when arr->cap >= cap.
 * Grows by doubling from max(current_cap, 8).  Asserts on overflow, on
 * a == NULL when reallocation is needed, and on arena OOM.
 */
static inline void ARRAY_RESERVE_(ARRAY_NAME *arr, uint32_t cap, rc_arena *a)
{
    if (cap <= arr->cap) return;
    uint32_t new_cap = arr->cap > 8 ? arr->cap : 8;
    while (new_cap < cap) {
        RC_ASSERT(new_cap <= UINT32_MAX / 2 && "array capacity overflow");
        new_cap *= 2;
    }
    RC_ASSERT((size_t)new_cap <= UINT32_MAX / sizeof(ARRAY_T) && "array byte size overflow");
    RC_ASSERT(a != NULL && "arena required when reallocating");
    void *p = rc_arena_realloc(a, arr->data,
                               (uint32_t)(arr->cap * sizeof(ARRAY_T)),
                               (uint32_t)(new_cap * sizeof(ARRAY_T)));
    RC_ASSERT(p != NULL && "arena OOM");
    arr->data = (ARRAY_T *)p;
    arr->cap  = new_cap;
}

/* Append val; return the index of the new element. */
static inline uint32_t ARRAY_PUSH_(ARRAY_NAME *arr, ARRAY_T val, rc_arena *a)
{
    uint32_t idx = arr->num;
    ARRAY_RESERVE_(arr, idx + 1, a);
    arr->data[idx] = val;
    arr->num = idx + 1;
    return idx;
}

/* Remove and return the last element.  Asserts num > 0.  No arena needed. */
static inline ARRAY_T ARRAY_POP_(ARRAY_NAME *arr)
{
    RC_ASSERT(arr->num > 0 && "pop on empty array");
    return arr->data[--arr->num];
}

/*
 * Append n elements from src; return the index of the first new element.
 * No-op (returns arr->num) when n == 0.
 */
static inline uint32_t ARRAY_PUSH_N_(ARRAY_NAME *arr, const ARRAY_T *src,
                                      uint32_t n, rc_arena *a)
{
    uint32_t idx = arr->num;
    if (n == 0) return idx;
    ARRAY_RESERVE_(arr, idx + n, a);
    memcpy(arr->data + idx, src, n * sizeof(ARRAY_T));
    arr->num += n;
    return idx;
}

/* Append all elements of view; return the index of the first new element. */
static inline uint32_t ARRAY_APPEND_VIEW_(ARRAY_NAME *arr, ARRAY_VIEW view,
                                           rc_arena *a)
{
    return ARRAY_PUSH_N_(arr, view.data, view.num, a);
}

/*
 * Resize to new_num elements.  New elements (if growing) are uninitialised.
 * Shrinking only adjusts num; capacity is unchanged.
 */
static inline void ARRAY_RESIZE_(ARRAY_NAME *arr, uint32_t new_num, rc_arena *a)
{
    ARRAY_RESERVE_(arr, new_num, a);
    arr->num = new_num;
}

/*
 * Insert val at index i, shifting arr[i..num) one place to the right.
 * Asserts i <= num.
 */
static inline void ARRAY_INSERT_(ARRAY_NAME *arr, uint32_t i, ARRAY_T val,
                                   rc_arena *a)
{
    RC_ASSERT(i <= arr->num && "insert index out of bounds");
    ARRAY_RESERVE_(arr, arr->num + 1, a);
    memmove(arr->data + i + 1, arr->data + i,
            (arr->num - i) * sizeof(ARRAY_T));
    arr->data[i] = val;
    arr->num++;
}

/*
 * Insert n zeroed elements at index i; return a pointer to the inserted range.
 * Asserts i <= num.  No-op (returns arr->data + i) when n == 0.
 */
static inline ARRAY_T *ARRAY_INSERT_N_ZERO_(ARRAY_NAME *arr, uint32_t i,
                                              uint32_t n, rc_arena *a)
{
    RC_ASSERT(i <= arr->num && "insert_n_zero index out of bounds");
    if (n == 0) return arr->data + i;
    ARRAY_RESERVE_(arr, arr->num + n, a);
    memmove(arr->data + i + n, arr->data + i,
            (arr->num - i) * sizeof(ARRAY_T));
    memset(arr->data + i, 0, n * sizeof(ARRAY_T));
    arr->num += n;
    return arr->data + i;
}

/*
 * Insert all elements of view at index i, shifting arr[i..num) right.
 * Asserts i <= num.  Behaviour is undefined if view overlaps arr->data.
 */
static inline void ARRAY_INSERT_VIEW_(ARRAY_NAME *arr, uint32_t i,
                                       ARRAY_VIEW view, rc_arena *a)
{
    RC_ASSERT(i <= arr->num && "insert_view index out of bounds");
    if (view.num == 0) return;
    ARRAY_RESERVE_(arr, arr->num + view.num, a);
    memmove(arr->data + i + view.num, arr->data + i,
            (arr->num - i) * sizeof(ARRAY_T));
    memcpy(arr->data + i, view.data, view.num * sizeof(ARRAY_T));
    arr->num += view.num;
}

/*
 * Remove element at index i and return it.  Shifts arr[i+1..num) left.
 * Asserts i < num.  No arena needed.
 */
static inline ARRAY_T ARRAY_REMOVE_(ARRAY_NAME *arr, uint32_t i)
{
    RC_ASSERT(i < arr->num && "remove index out of bounds");
    ARRAY_T val = arr->data[i];
    memmove(arr->data + i, arr->data + i + 1,
            (arr->num - i - 1) * sizeof(ARRAY_T));
    arr->num--;
    return val;
}

/*
 * Remove n elements starting at index i, shifting the tail left.
 * Asserts i + n <= num.  No arena needed.
 */
static inline void ARRAY_REMOVE_N_(ARRAY_NAME *arr, uint32_t i, uint32_t n)
{
    RC_ASSERT(i + n <= arr->num && "remove_n range out of bounds");
    memmove(arr->data + i, arr->data + i + n,
            (arr->num - i - n) * sizeof(ARRAY_T));
    arr->num -= n;
}

/*
 * O(1) unordered removal: copy arr[num-1] over arr[i], decrement num.
 * Returns the removed element.  Asserts i < num.  No arena needed.
 */
static inline ARRAY_T ARRAY_REMOVE_SWAP_(ARRAY_NAME *arr, uint32_t i)
{
    RC_ASSERT(i < arr->num && "remove_swap index out of bounds");
    ARRAY_T val  = arr->data[i];
    arr->data[i] = arr->data[--arr->num];
    return val;
}

/* ---- cleanup ---- */

#undef ARRAY_SPAN_AS_VIEW_
#undef ARRAY_AS_VIEW_
#undef ARRAY_AS_SPAN_
#undef ARRAY_VIEW_SUBVIEW_
#undef ARRAY_SPAN_SUBSPAN_
#undef ARRAY_SPAN_SUBVIEW_
#undef ARRAY_SUBSPAN_
#undef ARRAY_SUBVIEW_
#undef ARRAY_RESERVE_
#undef ARRAY_PUSH_
#undef ARRAY_POP_
#undef ARRAY_PUSH_N_
#undef ARRAY_APPEND_VIEW_
#undef ARRAY_RESIZE_
#undef ARRAY_INSERT_
#undef ARRAY_INSERT_N_ZERO_
#undef ARRAY_INSERT_VIEW_
#undef ARRAY_REMOVE_
#undef ARRAY_REMOVE_N_
#undef ARRAY_REMOVE_SWAP_

#undef ARRAY_NAME
#undef ARRAY_VIEW
#undef ARRAY_SPAN
#undef ARRAY_T
